# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'choseProject.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(689, 528)
        self.chosestyle = QtWidgets.QGroupBox(Dialog)
        self.chosestyle.setGeometry(QtCore.QRect(10, 10, 131, 481))
        self.chosestyle.setObjectName("chosestyle")
        self.choseprojectbutton1 = QtWidgets.QPushButton(self.chosestyle)
        self.choseprojectbutton1.setGeometry(QtCore.QRect(10, 20, 111, 41))
        self.choseprojectbutton1.setObjectName("choseprojectbutton1")
        self.choseprojectbutton1_2 = QtWidgets.QPushButton(self.chosestyle)
        self.choseprojectbutton1_2.setGeometry(QtCore.QRect(10, 70, 111, 41))
        self.choseprojectbutton1_2.setObjectName("choseprojectbutton1_2")
        self.choseprojectbutton1_3 = QtWidgets.QPushButton(self.chosestyle)
        self.choseprojectbutton1_3.setGeometry(QtCore.QRect(10, 120, 111, 41))
        self.choseprojectbutton1_3.setObjectName("choseprojectbutton1_3")
        self.choseprojectbutton1_4 = QtWidgets.QPushButton(self.chosestyle)
        self.choseprojectbutton1_4.setGeometry(QtCore.QRect(10, 170, 111, 41))
        self.choseprojectbutton1_4.setObjectName("choseprojectbutton1_4")
        self.choseprojectbutton1_5 = QtWidgets.QPushButton(self.chosestyle)
        self.choseprojectbutton1_5.setGeometry(QtCore.QRect(10, 220, 111, 41))
        self.choseprojectbutton1_5.setObjectName("choseprojectbutton1_5")
        self.choseprojectbutton1_6 = QtWidgets.QPushButton(self.chosestyle)
        self.choseprojectbutton1_6.setGeometry(QtCore.QRect(10, 270, 111, 41))
        self.choseprojectbutton1_6.setObjectName("choseprojectbutton1_6")
        self.choseprojectbutton1_7 = QtWidgets.QPushButton(self.chosestyle)
        self.choseprojectbutton1_7.setGeometry(QtCore.QRect(10, 320, 111, 41))
        self.choseprojectbutton1_7.setObjectName("choseprojectbutton1_7")
        self.scrollArea = QtWidgets.QScrollArea(Dialog)
        self.scrollArea.setGeometry(QtCore.QRect(150, 20, 501, 471))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 499, 469))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(Dialog)
        self.choseprojectbutton1.clicked.connect(Dialog.choseproject_1)
        self.choseprojectbutton1_2.clicked.connect(Dialog.choseproject_2)
        self.choseprojectbutton1_3.clicked.connect(Dialog.choseproject_3)
        self.choseprojectbutton1_4.clicked.connect(Dialog.choseproject_4)
        self.choseprojectbutton1_5.clicked.connect(Dialog.choseproject_5)
        self.choseprojectbutton1_6.clicked.connect(Dialog.choseproject_6)
        self.choseprojectbutton1_7.clicked.connect(Dialog.choseproject_7)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.chosestyle.setTitle(_translate("Dialog", "控件类型"))
        self.choseprojectbutton1.setText(_translate("Dialog", "Column"))
        self.choseprojectbutton1_2.setText(_translate("Dialog", "Heat Exchange"))
        self.choseprojectbutton1_3.setText(_translate("Dialog", "Pumps"))
        self.choseprojectbutton1_4.setText(_translate("Dialog", "Compressors"))
        self.choseprojectbutton1_5.setText(_translate("Dialog", "Reactors"))
        self.choseprojectbutton1_6.setText(_translate("Dialog", "Pips and Fittings"))
        self.choseprojectbutton1_7.setText(_translate("Dialog", "LNG"))
